#!/bin/bash
set -e

BASE_DIR="/mnt/d/Project_data/SPPL2A/Virtual_Screening_SPPL2a"
RESULTS_DIR="$BASE_DIR/analysis_results"

systems=(
    "control" 
    "aurigene_top1" "aurigene_top2" "aurigene_top3"
    "enamine_top1" "enamine_top2" "enamine_top3"
    "zinc_top1" "zinc_top2" "zinc_top3"
)

for sys in "${systems[@]}"; do
    echo "Processing SASA and Rg for $sys with PBC removal..."
    SYS_DIR="$BASE_DIR/$sys"
    OUT_DIR="$RESULTS_DIR/$sys"
    
    # Use the PBC-corrected trajectory generated by the RMSD script
    TRAJ="$OUT_DIR/no_pbc.xtc"
    NDX="$OUT_DIR/index.ndx"

    if [ -f "$TRAJ" ]; then
        # 1. SASA (Protein) - Group 1
        echo "1" | gmx sasa -f "$TRAJ" -s "$SYS_DIR/step7_1.tpr" -n "$NDX" -o "$OUT_DIR/sasa.xvg" -tu ns -quiet
        
        # 2. Radius of Gyration (Protein) - Group 1
        echo "1" | gmx gyrate -f "$TRAJ" -s "$SYS_DIR/step7_1.tpr" -n "$NDX" -o "$OUT_DIR/gyrate.xvg" -quiet
        
        echo "Finished $sys SASA/Rg"
    else
        echo "Error: Corrected trajectory not found for $sys. Run analyze_rmsd.sh first."
    fi
done
